### ISSUE TITLE
Authentication system

### ISSUE THREAD

**Issue by jsbroks** [jsbroks/coco-annotator#9]
### Tasks
- [x] Create an authentication page
  - [x] Register Form
  - [x] Login Fprm
  - [x] Form validation
- [x] Redirect unauthenticated traffic to login page
- [x] Require login for api endpoints
- [x] Endpoint access (based on role)
  - [x] datasets
  - [x] images
  - [x] categories
  - [x] annotations
  - [x] annotator
- [x] User endpoints
  - [ ] Delete
  - [x] View
  - [x] Edit Info
  - [x] Login
  - [x] Logout
  - [x] Register
- [x] Navbar user section
- [x] User settings page
- [x] Save annotator settings to user object
- [ ] Set user perferences to the annotatior
- [x] Admin control panel
  - [x] Create Users
  - [x] Delete Users
  - [x] View Users
  - [ ] Edit Users
  - [ ] Pagnation
- [x] vuex user module
- [x] Dataset share option
- [x] First user create set as admin
- [x] Rewrite api test cases to support users

### Roles
**Admin**
- Can edit, delete and view any dataset

**Owner**
- Can delete, and share datasets user created

**User**
- Can create, edit and view datasets shared with them
